steps:
  transportRequestUploadCTS:
    dockerImage: 'hdemirkale/fiori-node'
    deployToolDependencies: []
    changeManagement:
      endpoint: 'http://gclp0353.devint.net.sap:8001'
      credentialsId: 'CTS' # The ID under which the credentials are provided on Jenkins defaults to 'CM'
      clientOpts: '' # additional java options, e.g. '-Djavax.net.ssl.trustStore=/path/to/truststore.jks'
      client: '100'
    abapPackage: 'ZCICD'
    applicationName: 'ZSAPUI5CICD'
    applicationDescription: 'Your description'
  transportRequestReqIDFromGit:
    gitFrom: 'c680aa7'